# Generated by Django 2.2.5 on 2019-09-12 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category Name', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Source Name', max_length=50, unique=True)),
                ('src_type', models.TextField(choices=[('S', 'Savings Acct'), ('C', 'Credit Card')], help_text='Source Type', verbose_name='Source Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(help_text='Transaction Amount')),
                ('date', models.DateTimeField(help_text='Transaction Date')),
                ('desc', models.CharField(help_text='Description', max_length=200, verbose_name='Description')),
                ('typ', models.CharField(choices=[('CR', 'Credit'), ('DB', 'Debit')], help_text='Transaction Type', max_length=2)),
                ('pending', models.BooleanField(default=True, help_text='Is transaction cycle is pending?')),
                ('include_in_calcultion', models.BooleanField(default=True, help_text='Include in any calculations?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='emapp.Category')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='emapp.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
