# Generated by Django 2.2.5 on 2019-09-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cleared',
            field=models.BooleanField(default=True, help_text='is is cleared?'),
        ),
    ]
