# Generated by Django 2.2.5 on 2019-09-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0002_transaction_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='desc',
            field=models.CharField(help_text='description', max_length=200),
        ),
    ]
