# Generated by Django 2.2.5 on 2019-09-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cleared',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='loan',
        ),
        migrations.AddField(
            model_name='transaction',
            name='pending',
            field=models.BooleanField(default=True, help_text='is transaction cycle is pending?'),
        ),
    ]
