# Generated by Django 2.2.5 on 2019-09-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emapp', '0005_auto_20190911_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
